---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
ny_noaa =
  ny_noaa |>
  drop_na(tmin, tmax, prcp, snow) |>
  mutate(
    year = year(date),
    month = month(date)) |>
  filter(year == 2010) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Tmin vs Tmax in 2010

```{r}
ny_noaa |>
  filter(month == 1) |>
  mutate(
    label = str_c("Prcp", prcp, "\nSnow: ", snow)
  ) |>
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~snow, alpha = 0.5,
    text = ~ label,
    type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Preciptation by Month < 150 in 2010

```{r}
ny_noaa |>
  filter(prcp < 150) |>
  plot_ly(
    x = ~month, y = ~prcp, color = ~month,
    type = "box", colors = "viridis"
  )

```

### Total Snow by Month in 2010

```{r}
ny_noaa |>
  group_by(month) |>
  summarize(total_snow = sum(snow)) |>
  plot_ly(
    x = ~month, y = ~total_snow,
    type = "bar"
  )

```

