---
title: "plotly_hw"
author: "Casandra Laney"
date: "2025-10-29"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

library(lubridate)
library(patchwork)
library(p8105.datasets)
data("ny_noaa")
library(plotly)
```


```{r}
ny_noaa =
  ny_noaa |>
  drop_na(tmin, tmax, prcp, snow) |>
  mutate(
    year = year(date),
    month = month(date)) |>
  filter(year == 2010) 
```


## Scatterplot
```{r}
ny_noaa |>
  filter(month == 1) |>
  mutate(
    label = str_c("Prcp", prcp, "\nSnow: ", snow)
  ) |>
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~snow, alpha = 0.5,
    text = ~ label,
    type = "scatter", mode = "markers")

```


## Bar Plot

```{r}
ny_noaa |>
  filter(prcp < 150) |>
  plot_ly(
    x = ~month, y = ~prcp, color = ~month,
    type = "box", colors = "viridis"
  )

```

## Box Plot

```{r}
ny_noaa |>
  group_by(month) |>
  summarize(total_snow = sum(snow)) |>
  plot_ly(
    x = ~month, y = ~total_snow,
    type = "bar"
  )
```

